[package]
name = "server-side"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.5"
env_logger = "0.10.1"
log = "0.4.20"
